//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategyGame.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoGamer
    {
        public int ID { get; set; }
        public int GrupoID { get; set; }
        public int GamerID { get; set; }
    
        public virtual Gamer Gamer { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
