//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategyGame.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.GrupoGamer = new HashSet<GrupoGamer>();
            this.Partidas = new HashSet<Partidas>();
        }
    
        public int ID { get; set; }
        public int Nome_GRU { get; set; }
        public int PlataformaGameID { get; set; }
        public string Imagem_GRU { get; set; }
        public System.DateTime DataCadastro_GRU { get; set; }
        public bool Ativo_GRU { get; set; }
        public string Descricao_GRU { get; set; }
        public string Site_GRU { get; set; }
        public string Facebook_GRU { get; set; }
        public string Youtube_GRU { get; set; }
        public string Twitter_GRU { get; set; }
        public string Twitch_GRU { get; set; }
        public string Nivel_GRU { get; set; }
        public Nullable<int> Recomendacoes_GRU { get; set; }
    
        public virtual PlataformaGame PlataformaGame { get; set; }
        public virtual ICollection<GrupoGamer> GrupoGamer { get; set; }
        public virtual ICollection<Partidas> Partidas { get; set; }
    }
}
