//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategyGame.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partidas
    {
        public Partidas()
        {
            this.PartidasResultado = new HashSet<PartidasResultado>();
        }
    
        public int ID { get; set; }
        public int GrupoID { get; set; }
        public System.DateTime Horario { get; set; }
        public bool Juiz { get; set; }
        public int QuantidadePartidas { get; set; }
        public int Duracao { get; set; }
        public Nullable<bool> Premiacao { get; set; }
        public Nullable<bool> Pago { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual ICollection<PartidasResultado> PartidasResultado { get; set; }
    }
}
