//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategyGame.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plataforma
    {
        public Plataforma()
        {
            this.Plataforma_Game = new HashSet<Plataforma_Game>();
        }
    
        public System.Guid id { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Plataforma_Game> Plataforma_Game { get; set; }
    }
}
