//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategyGame.Dados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StrategyGameEntities : DbContext
    {
        public StrategyGameEntities()
            : base("name=StrategyGameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Game> Game { get; set; }
        public DbSet<Gamer> Gamer { get; set; }
        public DbSet<GamerGame> GamerGame { get; set; }
        public DbSet<Grupo> Grupo { get; set; }
        public DbSet<Plataforma> Plataforma { get; set; }
        public DbSet<GamerGrupo> GamerGrupo { get; set; }
        public DbSet<GrupoGamer> GrupoGamer { get; set; }
        public DbSet<Partidas> Partidas { get; set; }
        public DbSet<PlataformaGame> PlataformaGame { get; set; }
        public DbSet<PartidasResultado> PartidasResultado { get; set; }
    }
}
