//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrategyGame.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.GrupoGamer = new HashSet<GrupoGamer>();
            this.TorneioGrupoGamer = new HashSet<TorneioGrupoGamer>();
        }
    
        public int ID { get; set; }
        public int Nome_GRU { get; set; }
        public int PlataformaGameID { get; set; }
        public string Imagem_GRU { get; set; }
        public System.DateTime DataCadastro_GRU { get; set; }
        public bool Ativo_GRU { get; set; }
        public string Descricao_GRU { get; set; }
        public string Site_GRU { get; set; }
        public string Facebook_GRU { get; set; }
        public string Youtube_GRU { get; set; }
        public string Twitter_GRU { get; set; }
        public string Twitch_GRU { get; set; }
        public string Nivel_GRU { get; set; }
        public Nullable<int> Recomendacoes_GRU { get; set; }
        public int GamerID { get; set; }
    
        public virtual PlataformaGame PlataformaGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoGamer> GrupoGamer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TorneioGrupoGamer> TorneioGrupoGamer { get; set; }
    }
}
